### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jacobabiola** [connext/vector-router-docker-compose#5]
Hello,

Thanks for taking your time always to help.

Please i get this error when i do `docker-compose logs`

` 7 migrations found in prisma/migrations
node             |
node             | No pending migrations to apply.
node             | Starting node in prod-mode
node             | process.cwd():  /app
node             | No config file available...
node             | webpack:///./src/config.ts?:79
node             | for (const chainId of Object.keys(vectorConfig.chainProviders)) {
node             |                              ^
node             |
node             | TypeError: Cannot convert undefined or null to object
node             |     at Function.keys (<anonymous>)
node             |     at eval (webpack:///./src/config.ts?:79:30)
node             |     at Object../src/config.ts (/app/dist/bundle.js:19699:1)
node             |     at __webpack_require__ (/app/dist/bundle.js:20:30)
node             |     at eval (webpack:///./src/services/store.ts?:7:18)
node             |     at Object../src/services/store.ts (/app/dist/bundle.js:19781:1)
node             |     at __webpack_require__ (/app/dist/bundle.js:20:30)
node             |     at eval (webpack:///./src/index.ts?:17:17)
node             |     at Object../src/index.ts (/app/dist/bundle.js:19757:1)
node             |     at __webpack_require__ (/app/dist/bundle.js:20:30)
`

And here is my config.json file

{
  "adminToken": "....",
  "mnemonic": "..........",
  "chainProviders": {
    "1": "https://mainnet.infura.io/v3/..",
    "42": "https://kovan.infura.io/v3/..",
    "56": "https://bsc-dataseed.binance.org/",
    "97": "https://data-seed-prebsc-1-s2.binance.org:8545"
  },
  "logLevel": "info",
  "messagingUrl": "https://messaging.connext.network",
  "production": true,
  "allowedSwaps": [
    {
      "fromChainId": 42,
      "toChainId": 97,
      "fromAssetId": "0xb1F1d182eE0B9accE39AAe25cc48B24D8A6c496C",
      "toAssetId": "0xfde3946d100971a50a90c7e15b724e21938c59f8",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 97,
      "toChainId": 42,
      "fromAssetId": "0xfde3946d100971a50a90c7e15b724e21938c59f8",
      "toAssetId": "0xb1F1d182eE0B9accE39AAe25cc48B24D8A6c496C",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 1,
      "toChainId": 137,
      "fromAssetId": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "toAssetId": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 1,
      "fromAssetId": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
      "toAssetId": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 137,
      "fromAssetId": "0x55d398326f99059ff775485246999027b3197955",
      "toAssetId": "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 56,
      "fromAssetId": "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
      "toAssetId": "0x55d398326f99059ff775485246999027b3197955",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 100,
      "fromAssetId": "0x55d398326f99059ff775485246999027b3197955",
      "toAssetId": "0x4ecaba5870353805a9f068101a40e0f32ed605c6",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 56,
      "fromAssetId": "0x4ecaba5870353805a9f068101a40e0f32ed605c6",
      "toAssetId": "0x55d398326f99059ff775485246999027b3197955",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 137,
      "fromAssetId": "0x4ecaba5870353805a9f068101a40e0f32ed605c6",
      "toAssetId": "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 100,
      "fromAssetId": "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
      "toAssetId": "0x4ecaba5870353805a9f068101a40e0f32ed605c6",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 1,
      "toChainId": 100,
      "fromAssetId": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 1,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 137,
      "fromAssetId": "0xbf5140a22578168fd562dccf235e5d43a02ce9b1",
      "toAssetId": "0xb33eaad8d922b1083446dc23f610c2567fb5180f",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 56,
      "fromAssetId": "0xb33eaad8d922b1083446dc23f610c2567fb5180f",
      "toAssetId": "0xbf5140a22578168fd562dccf235e5d43a02ce9b1",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 100,
      "fromAssetId": "0xbf5140a22578168fd562dccf235e5d43a02ce9b1",
      "toAssetId": "0x4537e328bf7e4efa29d05caea260d7fe26af9d74",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 56,
      "fromAssetId": "0x4537e328bf7e4efa29d05caea260d7fe26af9d74",
      "toAssetId": "0xbf5140a22578168fd562dccf235e5d43a02ce9b1",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 137,
      "fromAssetId": "0x4537e328bf7e4efa29d05caea260d7fe26af9d74",
      "toAssetId": "0xb33eaad8d922b1083446dc23f610c2567fb5180f",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 100,
      "fromAssetId": "0xb33eaad8d922b1083446dc23f610c2567fb5180f",
      "toAssetId": "0x4537e328bf7e4efa29d05caea260d7fe26af9d74",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 137,
      "fromAssetId": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
      "toAssetId": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 56,
      "fromAssetId": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "toAssetId": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 100,
      "fromAssetId": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
      "toAssetId": "0xddafbb505ad214d7b80b1f830fccc89b60fb7a83",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 56,
      "fromAssetId": "0xddafbb505ad214d7b80b1f830fccc89b60fb7a83",
      "toAssetId": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 137,
      "fromAssetId": "0xddafbb505ad214d7b80b1f830fccc89b60fb7a83",
      "toAssetId": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 100,
      "fromAssetId": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "toAssetId": "0xddafbb505ad214d7b80b1f830fccc89b60fb7a83",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 137,
      "fromAssetId": "0x44fA8E6f47987339850636F88629646662444217",
      "toAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 100,
      "fromAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "toAssetId": "0x44fA8E6f47987339850636F88629646662444217",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 100,
      "fromAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 137,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 1,
      "toChainId": 137,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 56,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 100,
      "fromAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 137,
      "fromAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "toAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 56,
      "fromAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "toAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 128,
      "fromAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "toAssetId": "0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 128,
      "toChainId": 137,
      "fromAssetId": "0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047",
      "toAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 128,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 128,
      "toChainId": 100,
      "fromAssetId": "0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 128,
      "toChainId": 56,
      "fromAssetId": "0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047",
      "toAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 128,
      "fromAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "toAssetId": "0x0298c2b32eaE4da002a15f36fdf7615BEa3DA047",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 100,
      "fromAssetId": "0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 100,
      "fromAssetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
      "toAssetId": "0x4ECaBa5870353805a9F068101A40E0f32ed605C6",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 100,
      "fromAssetId": "0x04068da6c83afcfa0e13ba15a6696662335d5b75",
      "toAssetId": "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 250,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 250,
      "fromAssetId": "0x4ECaBa5870353805a9F068101A40E0f32ed605C6",
      "toAssetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 100,
      "toChainId": 250,
      "fromAssetId": "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83",
      "toAssetId": "0x04068da6c83afcfa0e13ba15a6696662335d5b75",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 137,
      "fromAssetId": "0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e",
      "toAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 137,
      "fromAssetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
      "toAssetId": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 137,
      "fromAssetId": "0x04068da6c83afcfa0e13ba15a6696662335d5b75",
      "toAssetId": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 250,
      "fromAssetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "toAssetId": "0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 250,
      "fromAssetId": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
      "toAssetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 137,
      "toChainId": 250,
      "fromAssetId": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
      "toAssetId": "0x04068da6c83afcfa0e13ba15a6696662335d5b75",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 56,
      "fromAssetId": "0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e",
      "toAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 56,
      "fromAssetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
      "toAssetId": "0x55d398326f99059fF775485246999027B3197955",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 250,
      "toChainId": 56,
      "fromAssetId": "0x04068da6c83afcfa0e13ba15a6696662335d5b75",
      "toAssetId": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 250,
      "fromAssetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "toAssetId": "0x8d11ec38a3eb5e956b052f67da8bdc9bef8abf3e",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 250,
      "fromAssetId": "0x55d398326f99059fF775485246999027B3197955",
      "toAssetId": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    },
    {
      "fromChainId": 56,
      "toChainId": 250,
      "fromAssetId": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
      "toAssetId": "0x04068da6c83afcfa0e13ba15a6696662335d5b75",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    }
  ],
  "rebalanceProfiles": [
    {
      "chainId": 56,
      "assetId": "0x55d398326f99059ff775485246999027b3197955",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 137,
      "assetId": "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 100,
      "assetId": "0x4ecaba5870353805a9f068101a40e0f32ed605c6",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 56,
      "assetId": "0xbf5140a22578168fd562dccf235e5d43a02ce9b1",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 137,
      "assetId": "0xb33eaad8d922b1083446dc23f610c2567fb5180f",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 100,
      "assetId": "0x4537e328bf7e4efa29d05caea260d7fe26af9d74",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 56,
      "assetId": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 137,
      "assetId": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 100,
      "assetId": "0xddafbb505ad214d7b80b1f830fccc89b60fb7a83",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 100,
      "assetId": "0x44fA8E6f47987339850636F88629646662444217",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 137,
      "assetId": "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 100,
      "assetId": "0x0000000000000000000000000000000000000000",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 137,
      "assetId": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 1,
      "assetId": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 137,
      "assetId": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 1,
      "assetId": "0x0000000000000000000000000000000000000000",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 1,
      "assetId": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 42,
      "assetId": "0xb1F1d182eE0B9accE39AAe25cc48B24D8A6c496C",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 56,
      "assetId": "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    {
      "chainId": 97,
      "assetId": "0xfde3946d100971a50a90c7e15b724e21938c59f8",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    },
    
  ],
  "skipCheckIn": true,
  "baseGasSubsidyPercentage": 0,
  "basePercentageFee": 0.05
}

**Comment by rhlsthrm** [comment]
Is the config being properly mounted into the container? Did you make any changes to docker-compose? Where is the config file located? It should be in `data/vectorConfig/config.json`.

**Comment by jacobabiola** [comment]
Thanks for the response, No, I did not make any changes to the docker-compose file. yes, the config file is located in the right directory as you mentioned above.
